apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: olomg48/front:latest
        ports:
        - containerPort: 8080
        env:
        - name: ApiBaseUrl
          value: http://apiport-srv:8000

---

apiVersion: v1
kind: Service
metadata:
  name: frontport-srv
spec:
  selector:
    app: front
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 8080
  type: NodePort