global:
  security:
    allowInsecureImages: true
apps:
  api:
    service:
      portName: http-python
      port: 8000
      targetPort: 8000
      nodePort: 30800
    deploy:
      replicas: 1
      image: olomg48/api:1.1
      containerPort: 8000
      env:
        INFERENCE_URL: "http://inference-srv:8000"
      secretEnv:
        DB_CONN:
          secretName: connection-string
          secretKey: string
      resources:
        requests:
          memory: "512Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
  inference:
    service:
      portName: http-python
      port: 8000
      targetPort: 8000
      nodePort: 30801
    deploy:
      replicas: 1
      image: olomg48/inference:1.0
      containerPort: 8000
      env:
        MLFLOW_TRACKING_URI: "https://mlflow.toadres.pl/"
      resources:
        requests:
          memory: "512Mi"
          cpu: "100m"
        limits:
          memory: "1024Mi"
          cpu: "500m"
  front:
    service:
      portName: http-dotnet
      port: 8080
      targetPort: 8080
      nodePort: 30880
    deploy:
      replicas: 1
      image: olomg48/front:b940d7894a0f6fce3475e2cab25fccd235665c85
      containerPort: 8080
      env:
        ApiBaseUrl: "http://api-srv:8000/api"
      resources:
        requests:
          memory: "512Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
  

ingress:
  default-ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: 
        paths:
          - path: /
            pathType: Prefix
            serviceName: front-srv
            servicePort: 8080

          - path: /api
            pathType: Prefix
            serviceName: api-srv
            servicePort: 8000

          - path: /inference
            pathType: Prefix
            serviceName: inference-srv
            servicePort: 8000

ingress-nginx:
  enabled: true
  controller:
    replicaCount: 1