apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30900 # API Minio dostępne na tym porcie hosta
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
      nodePort: 30901 # Konsola Minio UI
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio
        args: ["server", "/data", "--console-address", ":9001"]
        env:
        - name: MINIO_ROOT_USER
          value: "admin"
        - name: MINIO_ROOT_PASSWORD
          value: "password123"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - name: minio-data
          mountPath: /data
      volumes:
      - name: minio-data
        emptyDir: {} # Dla testów. Przy produkcji użyj PersistentVolumeClaim
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500 # MLFlow UI dostępne na tym porcie hosta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:latest
        workingDir: /mlflow
        command: ["/bin/sh", "-c"]
        args: 
          - >
            mlflow server 
            --backend-store-uri sqlite:///mlflow.db 
            --artifacts-destination s3://mlflow-bucket/ 
            --host 0.0.0.0 
            --serve-artifacts
            --allowed-hosts "*"
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "admin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "password123"
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://minio:9000" # Kluczowe: używamy nazwy Service Minio
        - name: MLFLOW_S3_IGNORE_CONFIG_FILE
          value: "true"
        - name: MLFLOW_PORT  # Nadpisujemy automatyczną zmienną K8s
          value: "5000"
        ports:
        - containerPort: 5000